sudo: required
services:
  - docker

stages:
  - delivery
  - submit

jobs:
  include:
    - stage: delivery
      if: type != pull_request
      env:
        - FOLDER=/package
        - PACKAGE_NAME=drbd-formula

      before_install:
        - docker pull shap/continuous_deliver:latest

      script:
        - |
          docker run -t -v "$(pwd):/package" -w /package \
          -e OBS_USER -e OBS_PASS -e FOLDER -e OBS_PROJECT -e PACKAGE_NAME \
          shap/continuous_deliver \
          /bin/bash -c "sed -i 's~%%VERSION%%~$TRAVIS_COMMIT~' _service && \
          sed -i 's~%%REPOSITORY%%~$TRAVIS_REPO_SLUG~' _service && \
          /scripts/upload.sh"

    - stage: submit
      if: type != pull_request AND branch = master
      env:
        - PACKAGE_NAME=drbd-formula

      before_install:
        - docker pull shap/continuous_deliver:latest

      script:
        - |
          docker run -t -v "$(pwd):/package" -w /package \
          -e OBS_USER -e OBS_PASS -e OBS_PROJECT -e PACKAGE_NAME -e TARGET_PROJECT shap/continuous_deliver \
          /scripts/submit.sh
